type GenericCertData = {
  barangayName: string;
  municipality: string;
  province: string;
  title: string;
  body: string;
  issuedToName: string;
  purpose: string;
  issuedAtText: string;
  captainName: string;
  secretaryName: string;
  controlNo: string;
};

export function buildGenericCertificateHTML(data: GenericCertData) {
  // Full HTML doc for iframe srcDoc
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${escapeHtml(data.title)}</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: Arial, sans-serif; color: #111; }
    .header { text-align:center; margin-bottom: 18px; }
    .h1 { font-size: 18px; font-weight: 700; letter-spacing: .4px; }
    .meta { font-size: 12px; margin-top: 6px; }
    .content { margin-top: 18px; font-size: 14px; line-height: 1.6; text-align: justify; }
    .sigRow { display:flex; justify-content: space-between; margin-top: 48px; }
    .sig { width: 44%; text-align:center; font-size: 12px; }
    .line { border-top: 1px solid #333; margin-top: 36px; padding-top: 6px; }
    .footer { margin-top: 22px; font-size: 11px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="h1">BARANGAY ${escapeHtml(data.barangayName)}</div>
    <div class="meta">${escapeHtml(data.municipality)}, ${escapeHtml(data.province)}</div>
    <div class="meta">Control No: ${escapeHtml(data.controlNo)}</div>
  </div>

  <div class="header">
    <div class="h1">${escapeHtml(data.title).toUpperCase()}</div>
  </div>

  <div class="content">
    <p>This is to certify that <b>${escapeHtml(data.issuedToName)}</b> is requesting this certificate for the purpose of <b>${escapeHtml(data.purpose)}</b>.</p>
    <p>${escapeHtml(data.body)}</p>
    <p>Issued this ${escapeHtml(data.issuedAtText)} at Barangay ${escapeHtml(data.barangayName)}, ${escapeHtml(data.municipality)}, ${escapeHtml(data.province)}.</p>
  </div>

  <div class="sigRow">
    <div class="sig">
      <div class="line"><b>${escapeHtml(data.secretaryName)}</b></div>
      Barangay Secretary
    </div>
    <div class="sig">
      <div class="line"><b>${escapeHtml(data.captainName)}</b></div>
      Punong Barangay
    </div>
  </div>

  <div class="footer">
    <div>Generated by BarangayOS • Powered by PLDT Enterprise & SpeedyPay</div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
