type PermitPrintData = {
  barangayName: string;
  municipality: string;
  province: string;

  businessName: string;
  ownerName: string;
  addressText: string;
  category?: string;

  year: number;
  feeAmount: number;
  orNo?: string;
  issuedAtText: string;
  controlNo: string;

  captainName: string;
  secretaryName: string;
};

export function buildBusinessPermitHTML(d: PermitPrintData) {
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Business Permit</title>
  <style>
    @page { size: A4; margin: 16mm; }
    body { font-family: Arial, sans-serif; color: #111; }
    .top { text-align:center; margin-bottom: 14px; }
    .h1 { font-size: 18px; font-weight: 800; letter-spacing: .5px; }
    .sub { font-size: 12px; margin-top: 4px; }
    .box { border: 1px solid #333; padding: 14px; border-radius: 8px; }
    .row { display:flex; gap: 14px; margin-top: 10px; }
    .col { flex: 1; }
    .label { font-size: 11px; color: #333; }
    .val { font-size: 14px; font-weight: 700; margin-top: 4px; }
    .sigRow { display:flex; justify-content: space-between; margin-top: 38px; }
    .sig { width: 44%; text-align:center; font-size: 12px; }
    .line { border-top: 1px solid #333; margin-top: 34px; padding-top: 6px; }
    .foot { margin-top: 18px; font-size: 11px; }
  </style>
</head>
<body>
  <div class="top">
    <div class="h1">BARANGAY ${esc(d.barangayName)}</div>
    <div class="sub">${esc(d.municipality)}, ${esc(d.province)}</div>
    <div class="sub"><b>BUSINESS PERMIT</b> • Year ${d.year}</div>
    <div class="sub">Control No: ${esc(d.controlNo)}</div>
  </div>

  <div class="box">
    <div class="row">
      <div class="col">
        <div class="label">Business Name</div>
        <div class="val">${esc(d.businessName)}</div>
      </div>
      <div class="col">
        <div class="label">Owner</div>
        <div class="val">${esc(d.ownerName)}</div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="label">Address</div>
        <div class="val">${esc(d.addressText)}</div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="label">Category</div>
        <div class="val">${esc(d.category ?? "-")}</div>
      </div>
      <div class="col">
        <div class="label">Fee</div>
        <div class="val">₱${Number(d.feeAmount).toFixed(2)}</div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <div class="label">OR No.</div>
        <div class="val">${esc(d.orNo ?? "-")}</div>
      </div>
      <div class="col">
        <div class="label">Issued</div>
        <div class="val">${esc(d.issuedAtText)}</div>
      </div>
    </div>
  </div>

  <div class="sigRow">
    <div class="sig">
      <div class="line"><b>${esc(d.secretaryName)}</b></div>
      Barangay Secretary
    </div>
    <div class="sig">
      <div class="line"><b>${esc(d.captainName)}</b></div>
      Punong Barangay
    </div>
  </div>

  <div class="foot">Generated by BarangayOS • Powered by PLDT Enterprise & SpeedyPay</div>
</body>
</html>`;
}

function esc(s: string) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
